spring:
  datasource:
    url:
      "jdbc:postgresql://localhost:4321/postgres"
    username:
      "postgres"
    password:
      "postgres"
  liquibase:
    changeLog: classpath:/db/changelog/changelog-master.xml